### ISSUE TITLE
t/taskqueue_retries.t may fail

### ISSUE THREAD

**Issue by eserte** [cpanel/cPanel-TaskQueue#34]
Sometimes the test suite fails like this:
```
#   Failed test 'Delayed appropriately'
#   at t/taskqueue_retries.t line 85.
#          got: '4'
#     expected: '3'
# Looks like you failed 1 test of 17.
t/taskqueue_retries.t ....................... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/17 subtests 
```

**Comment by toddr** [comment]
Reported in https://github.com/Perl/perl5/issues/19532 as:

t/taskqueue_pausing.t in CPANEL/cPanel-TaskQueue-0.902.tar.gz started to fail with perl 5.35.9:
```
#   Failed test 'Resume in other copy: TaskQueue is unpaused.'
#   at t/taskqueue_pausing.t line 46.
# Looks like you failed 1 test of 15.
t/taskqueue_pausing.t ....................... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/15 subtests 
```

First report at CPAN Testers: http://www.cpantesters.org/cpan/report/d8940380-99f0-11ec-81cf-263c376c1ca9
Overview of test reports: http://matrix.cpantesters.org/?dist=cPanel-TaskQueue%200.902

**Comment by atoomic** [comment]
This is exposing a bug in `cPanel::StateFile::_resynch` 

The test is using two `cPanel::TaskQueue` objects in 'paused' state.
And by running `resume_processing` on one object, it's expecting that the second object also resume.

The logic based on mtime and size is prone to race condition by design.
Disabling that check solves the issue.

This is strange that stripping that PV flag trigger that issue.
But I guess this is probably coming from the fact the code is now faster by skipping some OPs for the PV...

https://github.com/cpanel/cPanel-TaskQueue/blob/55494c86d45a671d3ec76d9fb7b8ac591ad70800/lib/cPanel/StateFile.pm#L462

```diff
diff --git a/lib/cPanel/StateFile.pm b/lib/cPanel/StateFile.pm
index dd8f235..14c50bf 100644
--- a/lib/cPanel/StateFile.pm
+++ b/lib/cPanel/StateFile.pm
@@ -459,7 +459,7 @@ sub import {
         }

         # CPANEL-11795: Timewarp safety.  If time moves backwards we can loop forever
-        if ( $self->{file_mtime} < $mtime || $self->{file_size} != $size || $self->{file_mtime} > time() ) {
+        if ( 1 ) {

             # File is newer or a different size
             $guard ||= cPanel::StateFile::Guard->new( { state => $self } );
```
